#  ---------------------------      Credit Card Fraud    ------------------
#  ------------------    Imbalanced Learning         -----------------

In this data this is a classfication probleam, So we our dependant value is "Class" Column.

##### Why Imbalance here?
1. as there are huge dependance in dependent values. 
2. for solving the problem we will use different method. which are...


1. #####  "Logistic Regression" model. In Imbalance dataset just don't only check accuarcy, with accuracy check confussion metrix, classification_report also.
2. "Cross Validation". because it is also the way to help to handle imbalance datset, where model will be apply on train dataset.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\amita\\Downloads\\Krish Naik\\feature engnieering\\creditCardFraud\\creditcard.csv\\creditcard.csv")
df.head()


Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [3]:
df.shape

(284807, 31)

In [4]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

this is classification probleam so we will check values counts of "Class" column, which is our dependant value in dataset

In [5]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [6]:
# dividing Independent & Dependent Features:

X = df.drop("Class", axis=1)
y = df.Class

In [7]:
X.shape


(284807, 30)

In [8]:
y.shape

(284807,)


#####  Imbalanced dataset doesn't impact on havily insamble techniques So, we should not use decision tree kind of algos.

#### after that let's apply any simple algorithm, which is Logistic Regression.
##### this is classification problem.

### 1. Cross Validation "KFold" algorithm:

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [10]:
10.0 **np.arange(-2,3)

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [11]:
# using "Logrithm" Classifier:

log_class = LogisticRegression()
grid = {'C':10.0 ** np.arange(-2,3), 'penalty':['l1', 'l2']}
# cv means "Cross Validation" algorithm applying here.
cv = KFold(n_splits=5, random_state= None, shuffle=False)


In [12]:
# Split the dataset into Train & test dataset: [70% - 30%]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)

In [13]:
clf = GridSearchCV(log_class, grid, cv=cv, n_jobs=-1, scoring='f1_macro')
clf.fit(X_train, y_train)

C:\Users\amita\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\amita\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\amita\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\amita\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 54, in _check_solver
    raise ValueError(
Value

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [14]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85247    45]
 [   51   100]]
0.9988764439450862
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85292
           1       0.69      0.66      0.68       151

    accuracy                           1.00     85443
   macro avg       0.84      0.83      0.84     85443
weighted avg       1.00      1.00      1.00     85443



In [15]:
347*100

34700

In [16]:
y_train.value_counts()

0    199023
1       341
Name: Class, dtype: int64

In [17]:
class_weight = dict({0:1, 1:100})

### 2. Random Forest Classifier algorithm:

In [18]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train, y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [19]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85288     4]
 [   35   116]]
0.9995435553526912
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85292
           1       0.97      0.77      0.86       151

    accuracy                           1.00     85443
   macro avg       0.98      0.88      0.93     85443
weighted avg       1.00      1.00      1.00     85443



## Under Sampling:

* we are using this method when 0 has 10000 points and 1 has 100 points which is imbalance dataset.
* now in under sampling we will reduce the 0's points where we will reduce 10000 points to 200 points or 100 points.
* for under sampling we will use "imblearn" library... for that..
    * in cmd: 
        pip install imbalanced-learn

In [20]:
# y_train.value_counts()

In [ ]:
# pip uninstall imbalanced-learn


In [ ]:
pip install -U imbalanced-learn

In [ ]:
# "Counter" is used for inshort the values. 

from collections import Counter
Counter(y_train)

In [1]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns=NearMiss(0.8)
X_train_ns, y_train_ns=ns.fit_resample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

TypeError: __init__() takes 1 positional argument but 2 were given

###  Under Sampling applying on Random forest algo

In Under Sampling model will increase the number of data which has low values. 
* Here, In this dataset 1 has less no of data, so Under Sampling will increse the data  in 1 points. and give us the accuracy and precision, recall.

In [41]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_ns, y_train_ns)

NameError: name 'X_train_ns' is not defined

### SMOTETomek:

* SMOTETomek is working like over sampling but here, Smotetomek is create the new points of the lowest number and probably looking around that near by the location.
* like here, points 1 has low no of values so it will increse the values of points 1 which is nearby location.

In [63]:
from imblearn.combine import SMOTETomek

In [64]:
os = SMOTETomek(0.75)
X_train_ns, y_train_ns = os.fit_sample(X_train, y_train)
print("The number of classes before fit{}".format(Counter(y_train)))
print("The number of classes after fit{}".format(Counter(y_train)))

TypeError: __init__() takes 1 positional argument but 2 were given

In [65]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_ns, y_train_ns)

NameError: name 'X_train_ns' is not defined

In [66]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

### Ensemble Techniques: 

In [67]:
from imblearn.ensemble import EasyEnsembleClassifier

In [69]:
easy=EasyEnsembleClassifier()
easy.fit(X_train, y_train)

EasyEnsembleClassifier()

In [70]:
y_pred=easy.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[82163  3141]
 [    8   131]]
0.9631450206570462
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     85304
           1       0.04      0.94      0.08       139

    accuracy                           0.96     85443
   macro avg       0.52      0.95      0.53     85443
weighted avg       1.00      0.96      0.98     85443

